### PR TITLE
feat: add name and url outputs on simple_bucket module

### PR DESCRIPTION
**Pull request by jbpaux**
Hi,

It would be nice to have the same outputs as the "multi cloud storage" module:
* Name of the storage account (to ensure dependency composition with main module or other modules)
* URL of the bucket

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@jbpaux
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
Checking for missing newline at end of file
Error: No newline at end of file ./modules/simple_bucket/outputs.tf
 ```

**Comment by comment-bot-dev** [comment]
@jbpaux
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jbpaux
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jbpaux
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]
LGTM - Thanks @jbpaux for the contribution!

**Pull request merged**
