### PR TITLE
provide is_live backwards compatibility

### LINKED ISSUE #89: Terraform Google Provider 3.41.0 Breaking Change for `is_live`
Hello,

Looks like the google terraform provider version 3.41.0 removed support for is_live:
https://github.com/hashicorp/terraform-provider-google/commit/d1014fe3b47d377db9a6eee9cfa9cbb0412c18e2#

We'll patch our local copy of the module but can you create an official release to remove this?
https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/main.tf#L102

Too bad terraform didn't provide the warning, looks like it was marked as "Removed" since July 2019.

Thanks

### PR DESCRIPTION
**Pull request by jaketf**
Fixes #89.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
main.tf
--- old/main.tf
+++ new/main.tf
@@ -96,8 +96,8 @@
         storage_class = lookup(lifecycle_rule.value.action, "storage_class", null)
       }
       condition {
-        age                   = lookup(lifecycle_rule.value.condition, "age", null)
-        created_before        = lookup(lifecycle_rule.value.condition, "created_before", null)
+        age            = lookup(lifecycle_rule.value.condition, "age", null)
+        created_before = lookup(lifecycle_rule.value.condition, "created_before", null)
         // provide backwards compatibility for those using is_live in this module and google provider > 3.41.0
         // https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/89
         with_state            = lookup(lifecycle_rule.value.condition, "with_state", lookup(lifecycle_rule.value.condition, "is_live", false) ? "LIVE" : null)
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Review by morgante — APPROVED** [review]
Looks great, just need to fix linters. Thanks!

**Review by morgante — CHANGES_REQUESTED** [review]
@jaketf Looks like the `simple_bucket` module also needs to be updated.

**Comment by morgante** [comment]
Superseded by #91.

**Pull request closed without merging**
