### PR TITLE
feat!: add cors segmentation

### PR DESCRIPTION
**Pull request by bruno561**
Adding the ability to segment CORS by buckets

#294

### CODE REVIEW

**Comment by bruno561** [comment]
Review, please?

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @bruno561! I have similar feedback as https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/297#discussion_r1552586580

**Comment by bruno561** [comment]
> Thanks for the PR @bruno561! I have similar feedback as [#297 (comment)](https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/297#discussion_r1552586580)

@bharathkkb answered.

**Comment by mehdicopter** [comment]
Could we reopen this PR please ?

**Comment by tonia-kas** [comment]
Any update of this?

**Pull request closed without merging**
