### PR TITLE
allow setting storage.admin and storage.hmacKeyAdmin roles

### LINKED ISSUE #18: Add more roles (for storage.buckets.get in particular)
Hi,

For apps ~to write to~ to download objects from GCS via a client lib, they seem to require `storage.buckets.get` access.

Please allow to bind additional roles that can provide this such as:

`roles/storage.admin`

and/or

`roles/storage.legacyBucket(Reader|Writer|Owner)`

https://cloud.google.com/storage/docs/access-control/iam-roles

Optional: Perhaps go as far as allowing the user to provide a `self_link` to a custom role

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
fixes #18

this adds changes from #22 which were not included in #86

also:
- improve existing variable descriptions and types
- update dev tools to: 0.12.0
- test/setup/main.tf: add skip_gcloud_download = true
- test/setup/main.tf: add missing iam.googleapis.com to activate_apis

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by adrian-gierakowski** [comment]
Any chance of getting this reviewed? Thanks!

**Comment by adrian-gierakowski** [comment]
ping :)

**Review by bharathkkb — APPROVED** [review]
LGTM 
We should consider revamping the root interface now that we have module for_each to support a single bucket and any arbitrary IAM roles, so we don't have a bool flag, map for each bucket and list for all buckets to collapse all IAM varriables.

**Comment by adrian-gierakowski** [comment]
can this be merged? I guess someone would have to trigger the CI job first?

**Pull request merged**
