### PR TITLE
fix default storage class

### PR DESCRIPTION
**Pull request by pharveybattelle**
Fixes https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/122

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
Note this will technically be a breaking change.

**Comment by pharveybattelle** [comment]
I guess anyone who hasn't changed the default will see what looks like a change happen, even though nothing will actually change since MULTI_REGIONAL = STANDARD.   I'm assume that most people had to override the default since it wasn't a good default.

**Comment by morgante** [comment]
Yeah, we need to flag it as a breaking change just because people will see a diff. But I'm comfortable with doing so.

**Review by morgante — APPROVED** [review]

**Pull request merged**
