### PR TITLE
fix: lookup default value for soft delete policy 

### PR DESCRIPTION
**Pull request by alexandre-abrioux**
This fix is a follow up to https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/309

# Issue

On a multi-bucket configuration, adding a `soft_delete_policy` configuration block like so:
```
  soft_delete_policy = {
    "bucket1" = {
      // Disable protection on this bucket
      retention_duration_seconds = 0
    }
    "bucket2" = {
      // Increase protection to the max value (90 days)
      retention_duration_seconds = 7776000
    }
  }
```
; results in the following error:
```
│ Error: Invalid function argument
│ 
│   on .terraform/modules/gcs.cloud_storage/main.tf line 160, in resource "google_storage_bucket" "buckets":
│  160:     for_each = [lookup(var.soft_delete_policy, each.value, {})]
│     ├────────────────
│     │ while calling lookup(inputMap, key, default...)
│ 
│ Invalid value for "default" parameter: the default value must have the same
│ type as the map elements.
```

# Fix

Instead of using an empty object `{}` as the default value of the lookup, we need to specify a complete object with every default value. The issue of not being able to use an empty object is described here: https://github.com/hashicorp/terraform/issues/35027

### CODE REVIEW

**Comment by jonathan-anyword** [comment]
Any update on this PR? need it also :)

**Comment by vdcadena553** [comment]
any updates here?

**Comment by flecno** [comment]
Would be great if this is fixed. As GCP will start billing the soft delete in September I really want to disable it for some buckets, created by this module.

**Comment by alexandre-abrioux** [comment]
Maybe @apeabody could help run CI and approve?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @alexandre-abrioux!

**Pull request merged**
