### PR TITLE
allow to use index key for iam member binding to prevent unknown instances when use resource attributes as member

### PR DESCRIPTION
**Pull request by cgroschupp**
We use the service account module as input for the iam_members in the module simple_bucket and get this error `Invalid for_each argument`:

Samples:
```terraform
module "service_accounts" {
  source        = "terraform-google-modules/service-accounts/google"
  version       = "~> 3.0"
  project_id    = "temp"
  prefix        = "tools"
  names         = ["bucket-viewer"]
}

module "name" {
  source     = "./terraform-google-cloud-storage//modules/simple_bucket"
  name       = "temp"
  location   = "europe-west1"
  project_id = "temp"
  iam_members = [{
    role   = "roles/storage.objectViewer"
    member = module.service_accounts.iam_email
  }]
  iam_members_use_index_key = false
}

```

Plan output:
```
 terraform plan

Error: Invalid for_each argument

  on .terraform/modules/name/modules/simple_bucket/main.tf line 80, in resource "google_storage_bucket_iam_member" "members":
  80:   for_each = local.iam_members

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

```terraform
module "service_accounts" {
  source        = "terraform-google-modules/service-accounts/google"
  version       = "~> 3.0"
  project_id    = "temp"
  prefix        = "tools"
  names         = ["bucket-viewer"]
}

module "name" {
  source     = "./terraform-google-cloud-storage//modules/simple_bucket"
  name       = "temp"
  location   = "europe-west1"
  project_id = "temp"
  iam_members = [{
    role   = "roles/storage.objectViewer"
    member = module.service_accounts.iam_email
  }]
  iam_members_use_index_key = true
}
```
Plan output:
```
terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.name.google_storage_bucket.bucket will be created
  + resource "google_storage_bucket" "bucket" {
      + bucket_policy_only          = (known after apply)
      + force_destroy               = false
      + id                          = (known after apply)
      + location                    = "EUROPE-WEST1"
      + name                        = "temp"
      + project                     = "temp"
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + uniform_bucket_level_access = true
      + url                         = (known after apply)

      + versioning {
          + enabled = true
        }
    }

  # module.name.google_storage_bucket_iam_member.members["roles/storage.objectViewer 0"] will be created
  + resource "google_storage_bucket_iam_member" "members" {
      + bucket = "temp"
      + etag   = (known after apply)
      + id     = (known after apply)
      + member = (known after apply)
      + role   = "roles/storage.objectViewer"
    }

  # module.service_accounts.data.template_file.keys["bucket-viewer"] will be read during apply
  # (config refers to values not yet known)
 <= data "template_file" "keys"  {
      + id       = (known after apply)
      + rendered = (known after apply)
      + template = "${key}"
      + vars     = {
          + "key" = ""
        }
    }

  # module.service_accounts.google_service_account.service_accounts["bucket-viewer"] will be created
  + resource "google_service_account" "service_accounts" {
      + account_id   = "tools-bucket-viewer"
      + display_name = "Terraform-managed service account"
      + email        = (known after apply)
      + id           = (known after apply)
      + name         = (known after apply)
      + project      = "temp"
      + unique_id    = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
One problem is when the order of the array `iam_members` is changed, then more resources are recreated than necessary.

Another solution is to use `count` instead of `for_each`, but this is a breaking change.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
I'm not sure we want to add this. It's meaningful additional complexity to support a (relatively) niche case and bug in Terraform.

If you need to dynamically assign a service account role, could you simply do it outside the module?

**Comment by cgroschupp** [comment]
yes, you are right, I have already solved this outside.
But i think this design problem of terraform, will follow us for a bit.
And I thought it might be helpful.

**Comment by morgante** [comment]
> yes, you are right, I have already solved this outside.
> But i think this design problem of terraform, will follow us for a bit.
> And I thought it might be helpful.

Yeah, I do appreciate the contribution. I just worry about expanding the scope of the module too much to work around Terraform's design flaws.

For now, I'm going to close this.

**Pull request closed without merging**
